// Physical key codes from Ghostty's libghostty-vt C API (`ghostty/src/input/key.zig`).

export enum KeyAction {
  RELEASE = 0,
  PRESS = 1,
  REPEAT = 2,
}

export enum Mods {
  NONE = 0,
  SHIFT = 1 << 0,
  CTRL = 1 << 1,
  ALT = 1 << 2,
  SUPER = 1 << 3,
  CAPSLOCK = 1 << 4,
  NUMLOCK = 1 << 5,
}

export enum Key {
  UNIDENTIFIED = 0,
  GRAVE = 1,
  BACKSLASH = 2,
  BRACKET_LEFT = 3,
  BRACKET_RIGHT = 4,
  COMMA = 5,
  ZERO = 6,
  ONE = 7,
  TWO = 8,
  THREE = 9,
  FOUR = 10,
  FIVE = 11,
  SIX = 12,
  SEVEN = 13,
  EIGHT = 14,
  NINE = 15,
  EQUAL = 16,
  A = 20,
  B = 21,
  C = 22,
  D = 23,
  E = 24,
  F = 25,
  G = 26,
  H = 27,
  I = 28,
  J = 29,
  K = 30,
  L = 31,
  M = 32,
  N = 33,
  O = 34,
  P = 35,
  Q = 36,
  R = 37,
  S = 38,
  T = 39,
  U = 40,
  V = 41,
  W = 42,
  X = 43,
  Y = 44,
  Z = 45,
  MINUS = 46,
  PERIOD = 47,
  QUOTE = 48,
  SEMICOLON = 49,
  SLASH = 50,
  BACKSPACE = 53,
  ENTER = 58,
  SPACE = 63,
  TAB = 64,
  DELETE = 68,
  END = 69,
  HOME = 71,
  INSERT = 72,
  PAGE_DOWN = 73,
  PAGE_UP = 74,
  DOWN = 75,
  LEFT = 76,
  RIGHT = 77,
  UP = 78,
  ESCAPE = 120,
  F1 = 121,
  F2 = 122,
  F3 = 123,
  F4 = 124,
  F5 = 125,
  F6 = 126,
  F7 = 127,
  F8 = 128,
  F9 = 129,
  F10 = 130,
  F11 = 131,
  F12 = 132,
}

const CODE_TO_KEY: Record<string, Key> = {
  Backquote: Key.GRAVE,
  Backslash: Key.BACKSLASH,
  BracketLeft: Key.BRACKET_LEFT,
  BracketRight: Key.BRACKET_RIGHT,
  Comma: Key.COMMA,
  Digit0: Key.ZERO,
  Digit1: Key.ONE,
  Digit2: Key.TWO,
  Digit3: Key.THREE,
  Digit4: Key.FOUR,
  Digit5: Key.FIVE,
  Digit6: Key.SIX,
  Digit7: Key.SEVEN,
  Digit8: Key.EIGHT,
  Digit9: Key.NINE,
  Equal: Key.EQUAL,
  KeyA: Key.A,
  KeyB: Key.B,
  KeyC: Key.C,
  KeyD: Key.D,
  KeyE: Key.E,
  KeyF: Key.F,
  KeyG: Key.G,
  KeyH: Key.H,
  KeyI: Key.I,
  KeyJ: Key.J,
  KeyK: Key.K,
  KeyL: Key.L,
  KeyM: Key.M,
  KeyN: Key.N,
  KeyO: Key.O,
  KeyP: Key.P,
  KeyQ: Key.Q,
  KeyR: Key.R,
  KeyS: Key.S,
  KeyT: Key.T,
  KeyU: Key.U,
  KeyV: Key.V,
  KeyW: Key.W,
  KeyX: Key.X,
  KeyY: Key.Y,
  KeyZ: Key.Z,
  Minus: Key.MINUS,
  Period: Key.PERIOD,
  Quote: Key.QUOTE,
  Semicolon: Key.SEMICOLON,
  Slash: Key.SLASH,
  Backspace: Key.BACKSPACE,
  Enter: Key.ENTER,
  NumpadEnter: Key.ENTER,
  Space: Key.SPACE,
  Tab: Key.TAB,
  Delete: Key.DELETE,
  End: Key.END,
  Home: Key.HOME,
  Insert: Key.INSERT,
  PageDown: Key.PAGE_DOWN,
  PageUp: Key.PAGE_UP,
  ArrowDown: Key.DOWN,
  ArrowLeft: Key.LEFT,
  ArrowRight: Key.RIGHT,
  ArrowUp: Key.UP,
  Escape: Key.ESCAPE,
  F1: Key.F1,
  F2: Key.F2,
  F3: Key.F3,
  F4: Key.F4,
  F5: Key.F5,
  F6: Key.F6,
  F7: Key.F7,
  F8: Key.F8,
  F9: Key.F9,
  F10: Key.F10,
  F11: Key.F11,
  F12: Key.F12,
};

export function keyFromCode(code: string): Key {
  return CODE_TO_KEY[code] ?? Key.UNIDENTIFIED;
}

export function modsFromEvent(event: {
  shiftKey: boolean;
  ctrlKey: boolean;
  altKey: boolean;
  metaKey: boolean;
}): number {
  let mods = Mods.NONE;
  if (event.shiftKey) mods |= Mods.SHIFT;
  if (event.ctrlKey) mods |= Mods.CTRL;
  if (event.altKey) mods |= Mods.ALT;
  if (event.metaKey) mods |= Mods.SUPER;
  return mods;
}
