export const DEFAULT_SUBAGENT_CHILD_DEADLINE_MS = 10 * 60_000;
export const DEFAULT_SUBAGENT_CANCELLATION_GRACE_MS = 5_000;
export const MAX_SUBAGENT_CHILD_TURNS = 24;
export const MAX_SUBAGENT_CHILD_TOOL_CALLS = 64;
export const MAX_SUBAGENT_CHILD_EVENTS = 512;
export const MAX_SUBAGENT_CHILD_OUTPUT_CHARS = 120_000;
export const MAX_SUBAGENT_CHILD_PROTOCOL_CHARS = 512_000;
