/**
 * Adapted from t3code packages/contracts/src/device.ts and
 * apps/web/src/components/settings/deviceHostConnectionChecks.ts @ a6ec88f7 (MIT)
 *
 * SSH device hosts and helper tool versions cross the renderer ↔ main boundary
 * only through these fail-closed shapes. A host is the user's own SSH target:
 * an alias from `~/.ssh/config` or `user@host`, plus an optional identity file
 * and port. Aiden stores no keys or passwords; the system `ssh` authenticates.
 */

/** SSH host ids are generated by Aiden; `local` is reserved for this Mac. */
export const SSH_DEVICE_HOST_ID_PATTERN = /^ssh-[a-z0-9]{6,40}$/u;
const SSH_TARGET_PATTERN = /^[^\s-][^\s]*$/u;
const MAX_LABEL_LENGTH = 80;
const MAX_TARGET_LENGTH = 255;
const MAX_IDENTITY_FILE_LENGTH = 1024;
export const MAX_SSH_DEVICE_HOSTS = 16;

export interface SshDeviceHostConfig {
  id: string;
  label: string;
  /** `user@host` or a `~/.ssh/config` alias. Never starts with `-`, so it cannot become an ssh option. */
  target: string;
  identityFile?: string;
  port?: number;
}

/** What the host editor holds while the user types. */
export interface SshDeviceHostDraft {
  id: string;
  label: string;
  target: string;
  identityFile: string;
  port: string;
}

export type SshDeviceHostDraftErrors = Partial<Record<"label" | "target" | "identityFile" | "port", string>>;

function hasControlCharacter(value: string): boolean {
  return Array.from(value).some((character) => {
    const code = character.charCodeAt(0);
    return code < 32 || code === 127;
  });
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

/** Validates a draft field by field, so the editor can show each problem beside its input. */
export function validateSshDeviceHostDraft(
  draft: SshDeviceHostDraft,
): { config: SshDeviceHostConfig; errors?: undefined } | { config?: undefined; errors: SshDeviceHostDraftErrors } {
  const errors: SshDeviceHostDraftErrors = {};
  const target = draft.target.trim();
  const label = draft.label.trim() || target;
  const identityFile = draft.identityFile.trim();
  const portText = draft.port.trim();
  if (!target) errors.target = "Enter an SSH alias or user@host.";
  else if (target.length > MAX_TARGET_LENGTH || !SSH_TARGET_PATTERN.test(target) || hasControlCharacter(target)) {
    errors.target = "Use an SSH alias or user@host without spaces, and not starting with a dash.";
  }
  if (label.length > MAX_LABEL_LENGTH || hasControlCharacter(label)) {
    errors.label = `Use a name of ${MAX_LABEL_LENGTH} characters or fewer.`;
  }
  if (identityFile) {
    if (identityFile.length > MAX_IDENTITY_FILE_LENGTH || hasControlCharacter(identityFile)) {
      errors.identityFile = "Enter the path to a private key file.";
    } else if (!identityFile.startsWith("/") && !identityFile.startsWith("~/")) {
      errors.identityFile = "Use an absolute path or one starting with ~/.";
    }
  }
  let port: number | undefined;
  if (portText) {
    port = /^[0-9]{1,5}$/u.test(portText) ? Number(portText) : Number.NaN;
    if (!Number.isInteger(port) || port < 1 || port > 65_535) errors.port = "Use a port from 1 to 65535.";
  }
  if (!SSH_DEVICE_HOST_ID_PATTERN.test(draft.id)) errors.target ??= "This host could not be saved. Close the editor and try again.";
  if (Object.keys(errors).length > 0) return { errors };
  return {
    config: {
      id: draft.id,
      label,
      target,
      ...(identityFile ? { identityFile } : {}),
      ...(port === undefined ? {} : { port }),
    },
  };
}

export function sshDeviceHostDraft(config: SshDeviceHostConfig): SshDeviceHostDraft {
  return {
    id: config.id,
    label: config.label,
    target: config.target,
    identityFile: config.identityFile ?? "",
    port: config.port === undefined ? "" : String(config.port),
  };
}

export function parseSshDeviceHostConfig(value: unknown): SshDeviceHostConfig | null {
  if (!isRecord(value)) return null;
  const { id, label, target, identityFile, port } = value;
  if (typeof id !== "string" || typeof label !== "string" || typeof target !== "string") return null;
  if (identityFile !== undefined && typeof identityFile !== "string") return null;
  if (port !== undefined && typeof port !== "number") return null;
  const result = validateSshDeviceHostDraft({
    id,
    label,
    target,
    identityFile: identityFile ?? "",
    port: port === undefined ? "" : String(port),
  });
  // A stored label must already be trimmed and present; the draft fallback to the target is for typing only.
  if (!result.config || result.config.label !== label || result.config.target !== target) return null;
  return result.config;
}

/** Hosts with unique ids, or null when any entry is invalid. */
export function parseSshDeviceHostConfigs(value: unknown): SshDeviceHostConfig[] | null {
  if (!Array.isArray(value) || value.length > MAX_SSH_DEVICE_HOSTS) return null;
  const hosts: SshDeviceHostConfig[] = [];
  const ids = new Set<string>();
  for (const item of value) {
    const host = parseSshDeviceHostConfig(item);
    if (!host || ids.has(host.id)) return null;
    ids.add(host.id);
    hosts.push(host);
  }
  return hosts;
}

/** Two configs reach the same machine the same way, so testing one tests the other. */
export function sshDeviceHostConnectionKey(host: Pick<SshDeviceHostConfig, "target" | "port" | "identityFile">): string {
  return JSON.stringify([host.target.trim(), host.port ?? null, host.identityFile?.trim() || null]);
}

/**
 * Applies one add, edit, or removal. An edit keeps the host's id so its
 * sessions and agent config stay attached; a second host with the same
 * destination is refused, since both would share one remote owner.
 */
export function updateSshDeviceHosts(
  hosts: readonly SshDeviceHostConfig[],
  host: SshDeviceHostConfig,
  remove = false,
): SshDeviceHostConfig[] {
  if (remove) return hosts.filter((candidate) => candidate.id !== host.id);
  const key = sshDeviceHostConnectionKey(host);
  if (hosts.some((candidate) => candidate.id !== host.id && sshDeviceHostConnectionKey(candidate) === key)) {
    throw new Error("Another SSH host already uses this destination.");
  }
  if (hosts.some((candidate) => candidate.id === host.id)) {
    return hosts.map((candidate) => (candidate.id === host.id ? { ...host } : candidate));
  }
  if (hosts.length >= MAX_SSH_DEVICE_HOSTS) throw new Error(`Aiden supports up to ${MAX_SSH_DEVICE_HOSTS} SSH hosts.`);
  return [...hosts, { ...host }];
}

// ---------------------------------------------------------------------------
// Helper tool versions (adapted from T3 DeviceToolVersions)
// ---------------------------------------------------------------------------

export interface DeviceToolVersion {
  /** The version this Aiden release pins. */
  requiredVersion: string;
  /** Completed installs on the host, oldest first. */
  installedVersions: string[];
  /** The version a running helper was started from, or null when it is not running. */
  runningVersion: string | null;
}

export interface DeviceToolVersions {
  hub: DeviceToolVersion;
  agent: DeviceToolVersion;
}

const TOOL_VERSION_PATTERN = /^[0-9A-Za-z.+-]{1,64}$/u;

function isToolVersion(value: unknown): value is string {
  return typeof value === "string" && TOOL_VERSION_PATTERN.test(value);
}

function parseToolVersion(value: unknown): DeviceToolVersion | null {
  if (!isRecord(value)) return null;
  const { requiredVersion, installedVersions, runningVersion } = value;
  if (!isToolVersion(requiredVersion)) return null;
  if (!Array.isArray(installedVersions) || installedVersions.length > 64) return null;
  if (!installedVersions.every(isToolVersion)) return null;
  if (runningVersion !== null && !isToolVersion(runningVersion)) return null;
  return { requiredVersion, installedVersions: [...installedVersions], runningVersion };
}

export function parseDeviceToolVersions(value: unknown): DeviceToolVersions | null {
  if (!isRecord(value)) return null;
  const hub = parseToolVersion(value.hub);
  const agent = parseToolVersion(value.agent);
  return hub && agent ? { hub, agent } : null;
}

const compareVersions = (left: string, right: string) => left.localeCompare(right, "en", { numeric: true });

/** The newest completed install other than the pinned one, used to word an update. */
export function previousToolVersion(tool: DeviceToolVersion): string | null {
  if (tool.runningVersion && tool.runningVersion !== tool.requiredVersion) return tool.runningVersion;
  const older = tool.installedVersions.filter((version) => version !== tool.requiredVersion).sort(compareVersions);
  return older[older.length - 1] ?? null;
}

/** The pinned version is missing but an older one is installed: an update rather than a first install. */
export function toolNeedsUpdate(tool: DeviceToolVersion | undefined): boolean {
  return Boolean(tool && !tool.installedVersions.includes(tool.requiredVersion) && previousToolVersion(tool));
}

/** The pinned version is not installed on the host at all. */
export function toolMissing(tool: DeviceToolVersion | undefined): boolean {
  return Boolean(tool && !tool.installedVersions.includes(tool.requiredVersion));
}

/** Progress copy for an install, worded as an update when an older version is on the host. */
export function deviceToolInstallMessage(name: string, tool: DeviceToolVersion | undefined): string {
  if (!tool) return `Installing ${name}…`;
  const previous = previousToolVersion(tool);
  return previous && !tool.installedVersions.includes(tool.requiredVersion)
    ? `Updating ${name} from ${previous} to ${tool.requiredVersion}…`
    : `Installing ${name} ${tool.requiredVersion}…`;
}

// ---------------------------------------------------------------------------
// Connection checks (adapted from T3 deviceHostConnectionChecks)
// ---------------------------------------------------------------------------

export interface DeviceHostPlatformCheck {
  platform: "ios";
  available: boolean;
  reason?: string;
}

/** The result of **Test connection**. It never installs or starts anything on the host. */
export type DeviceHostCheck =
  | { status: "pending" }
  /** The target resolves to this Mac; its simulators already appear under This Mac. */
  | { status: "local" }
  | { status: "connected"; nodeVersion: string; platforms: DeviceHostPlatformCheck[]; tools?: DeviceToolVersions }
  | { status: "failed"; error: string };

const MAX_CHECK_ERROR_LENGTH = 4000;

export function parseDeviceHostCheck(value: unknown): DeviceHostCheck | null {
  if (!isRecord(value)) return null;
  switch (value.status) {
    case "local":
      return { status: "local" };
    case "failed":
      return typeof value.error === "string" && value.error
        ? { status: "failed", error: value.error.slice(0, MAX_CHECK_ERROR_LENGTH) }
        : null;
    case "connected": {
      if (typeof value.nodeVersion !== "string" || !TOOL_VERSION_PATTERN.test(value.nodeVersion)) return null;
      if (!Array.isArray(value.platforms) || value.platforms.length > 4) return null;
      const platforms: DeviceHostPlatformCheck[] = [];
      for (const item of value.platforms) {
        if (!isRecord(item) || item.platform !== "ios" || typeof item.available !== "boolean") return null;
        if (item.reason !== undefined && typeof item.reason !== "string") return null;
        platforms.push({
          platform: "ios",
          available: item.available,
          ...(typeof item.reason === "string" ? { reason: item.reason } : {}),
        });
      }
      let tools: DeviceToolVersions | undefined;
      if (value.tools !== undefined) {
        const parsed = parseDeviceToolVersions(value.tools);
        if (!parsed) return null;
        tools = parsed;
      }
      return { status: "connected", nodeVersion: value.nodeVersion, platforms, ...(tools ? { tools } : {}) };
    }
    default:
      return null;
  }
}

/** One line for the editor and the host row, so a check reads the same everywhere. */
export function describeDeviceHostCheck(check: DeviceHostCheck): string {
  switch (check.status) {
    case "pending":
      return "Checking the connection…";
    case "local":
      return "This target is this Mac. Its simulators already appear under This Mac.";
    case "failed":
      return check.error;
    case "connected": {
      const ios = check.platforms.find((platform) => platform.platform === "ios");
      const platformLine = ios?.available
        ? "iOS Simulators available."
        : (ios?.reason ?? "iOS Simulators are unavailable on this host.");
      return `Connected. Node ${check.nodeVersion}. ${platformLine}`;
    }
  }
}
